const brands=["CHINT","Selec","Lotus","Tibcon","Litmus","Delixi","Industrial","Repair Spares"];
const collections=[
{title:"Home & Building Essentials",text:"Protection devices, wiring and core electrical products for homes, shops and buildings.",image:"assets/product-breaker.svg",tag:"Protection • Wiring",category:"Protection"},
{title:"Panel & Industrial Control",text:"Contactors, overloads, relays, timers, sensors and other control products for panels and machines.",image:"assets/product-contactor.svg",tag:"Control • Automation",category:"Control & Panel"},
{title:"Repair & Service Parts",text:"Capacitors, bearings, seals, submersible parts and maintenance essentials.",image:"assets/product-bearing.svg",tag:"Repair • Spares",category:"Bearings & Spares"}
];
const categories=[
{name:"Wires & Cables",icon:"〰",desc:"Winding, house wiring, multicore, power and submersible cables.",image:"assets/product-wire.svg"},
{name:"Protection",icon:"⚡",desc:"MCB, MCCB, RCCB, RCBO, SPD, fuses and changeover.",image:"assets/product-breaker.svg"},
{name:"Control & Panel",icon:"▦",desc:"Contactors, relays, overloads, push buttons and panel accessories.",image:"assets/product-contactor.svg"},
{name:"Automation",icon:"⌁",desc:"Timers, sensors, controllers, meters, PLC accessories and VFDs.",image:"assets/product-automation.svg"},
{name:"Capacitors",icon:"◫",desc:"Motor, refrigerator, submersible and power-factor capacitors.",image:"assets/product-capacitor.svg"},
{name:"Motors & Pumps",icon:"◉",desc:"Motors, water pumps, submersible motors and related parts.",image:"assets/product-motor.svg"},
{name:"Bearings & Spares",icon:"⊙",desc:"Bearings, seals and repair spares for electrical equipment.",image:"assets/product-bearing.svg"},
{name:"Lighting & Electronics",icon:"✦",desc:"LED lighting, drivers, electronic parts and selected HT items.",image:"assets/product-light.svg"}
];
const products=[
{id:1,brand:"Lotus",name:"Enamel Copper Winding Wire",model:"Super Enamel",spec:"Motor & transformer rewinding",cat:"Wires & Cables",code:"YK-WIR-001",desc:"Copper winding wire for rewinding and repair applications.",img:"assets/product-wire.svg",badge:"Popular",featured:true,tags:"lotus copper winding motor transformer wire rewind"},
{id:2,brand:"Lotus",name:"Submersible Winding Wire",model:"PVC / Poly",spec:"Submersible motor use",cat:"Wires & Cables",code:"YK-WIR-002",desc:"Insulated winding wire for submersible motor applications.",img:"assets/product-wire.svg",badge:"Workshop",featured:false,tags:"lotus submersible winding pvc poly wire"},
{id:3,brand:"Litmus",name:"House Wiring Cable",model:"Building Wire",spec:"Residential & commercial",cat:"Wires & Cables",code:"YK-WIR-003",desc:"Electrical cable for house, office and shop wiring.",img:"assets/product-wire.svg",badge:"Best Seller",featured:true,tags:"litmus house wiring cable copper building wire"},
{id:4,brand:"CHINT",name:"Miniature Circuit Breaker (MCB)",model:"NB1 Series",spec:"6A–63A • SP/DP",cat:"Protection",code:"YK-PRO-001",desc:"Compact circuit protection for distribution boards and small installations.",img:"assets/product-breaker.svg",badge:"Top Pick",featured:true,tags:"chint mcb breaker single pole double pole 32a 63a"},
{id:5,brand:"CHINT",name:"Moulded Case Circuit Breaker (MCCB)",model:"NM8",spec:"100A–250A • 3P/4P",cat:"Protection",code:"YK-PRO-002",desc:"Industrial circuit breaker for higher-capacity distribution.",img:"assets/product-breaker.svg",badge:"Industrial",featured:true,tags:"chint mccb breaker industrial 3p 4p"},
{id:6,brand:"CHINT",name:"RCCB / RCBO",model:"NXBLE / NL1",spec:"Leakage protection",cat:"Protection",code:"YK-PRO-003",desc:"Leakage and overload protection for safer installations.",img:"assets/product-breaker.svg",badge:"Safety",featured:false,tags:"chint rccb rcbo earth leakage breaker"},
{id:7,brand:"CHINT",name:"Surge Protection Device",model:"NU6",spec:"Panel surge safety",cat:"Protection",code:"YK-PRO-004",desc:"Surge protection for electrical panels and sensitive equipment.",img:"assets/product-breaker.svg",badge:"Protection",featured:false,tags:"chint spd surge protector lightning"},
{id:8,brand:"CHINT",name:"AC Contactor",model:"NC1",spec:"9A–40A • 220V coil",cat:"Control & Panel",code:"YK-CTL-001",desc:"Motor switching contactor for starters and control panels.",img:"assets/product-contactor.svg",badge:"Popular",featured:true,tags:"chint contactor starter coil 220v 415v"},
{id:9,brand:"CHINT",name:"Thermal Overload Relay",model:"NR2",spec:"Adjustable motor protection",cat:"Control & Panel",code:"YK-CTL-002",desc:"Overload relay for motor control and protection.",img:"assets/product-contactor.svg",badge:"Panel",featured:false,tags:"chint overload relay motor protection"},
{id:10,brand:"Industrial",name:"Push Button NO / NC",model:"22mm",spec:"Start / Stop / Reset",cat:"Control & Panel",code:"YK-CTL-003",desc:"Push buttons for control panels and machinery operations.",img:"assets/product-contactor.svg",badge:"Essential",featured:false,tags:"push button no nc red green start stop"},
{id:11,brand:"Industrial",name:"Terminal Blocks",model:"DIN Rail",spec:"Panel wiring accessory",cat:"Control & Panel",code:"YK-CTL-004",desc:"DIN rail terminal blocks for clean and organized panel wiring.",img:"assets/product-contactor.svg",badge:"Panel",featured:false,tags:"terminal block din rail panel"},
{id:12,brand:"Selec",name:"Digital Timer",model:"800 Series",spec:"Delay / cyclic control",cat:"Automation",code:"YK-AUT-001",desc:"Timing control for machinery, panels and automation.",img:"assets/product-automation.svg",badge:"Automation",featured:true,tags:"selec timer digital relay automation"},
{id:13,brand:"Selec",name:"Temperature Controller",model:"TC544AX",spec:"PID temperature control",cat:"Automation",code:"YK-AUT-002",desc:"Temperature control for ovens, heaters and machines.",img:"assets/product-automation.svg",badge:"Smart Control",featured:true,tags:"selec temperature controller pid thermocouple"},
{id:14,brand:"Industrial",name:"Proximity Sensor",model:"PNP / NPN",spec:"Inductive sensing",cat:"Automation",code:"YK-AUT-003",desc:"Industrial proximity sensor for machine automation.",img:"assets/product-automation.svg",badge:"Sensor",featured:false,tags:"sensor proximity pnp npn inductive"},
{id:15,brand:"Industrial",name:"Variable Frequency Drive (VFD)",model:"Motor Drive",spec:"Speed control",cat:"Automation",code:"YK-AUT-004",desc:"Motor speed control drive for industrial applications.",img:"assets/product-automation.svg",badge:"Industrial",featured:true,tags:"vfd inverter drive motor speed"},
{id:16,brand:"Tibcon",name:"Motor Run Capacitor",model:"CBB60",spec:"Fan / pump / motor",cat:"Capacitors",code:"YK-CAP-001",desc:"Run capacitor for motors, pumps and electrical equipment.",img:"assets/product-capacitor.svg",badge:"Fast Moving",featured:true,tags:"tibcon capacitor motor fan mfd uf"},
{id:17,brand:"Tibcon",name:"Submersible Capacitor",model:"Control Box Type",spec:"Submersible pump use",cat:"Capacitors",code:"YK-CAP-002",desc:"Capacitor for submersible pump control boxes.",img:"assets/product-capacitor.svg",badge:"Repair",featured:false,tags:"tibcon submersible capacitor mfd control box"},
{id:18,brand:"Tibcon",name:"Power Factor Capacitor",model:"PFC Type",spec:"Industrial correction",cat:"Capacitors",code:"YK-CAP-003",desc:"Industrial capacitor used for power-factor correction panels.",img:"assets/product-capacitor.svg",badge:"Industrial",featured:false,tags:"power factor capacitor kvar panel"},
{id:19,brand:"Industrial",name:"Water Pump",model:"Domestic / Commercial",spec:"Water transfer",cat:"Motors & Pumps",code:"YK-MOT-001",desc:"Water pump options for domestic and commercial use.",img:"assets/product-motor.svg",badge:"Utility",featured:false,tags:"pump water motor centrifugal"},
{id:20,brand:"Industrial",name:"Submersible Motor",model:"Water System",spec:"Borewell / water use",cat:"Motors & Pumps",code:"YK-MOT-002",desc:"Submersible motor solutions for water systems.",img:"assets/product-motor.svg",badge:"Pumping",featured:true,tags:"submersible motor pump"},
{id:21,brand:"Repair Spares",name:"6204 Bearing",model:"Deep Groove",spec:"Motor & machinery use",cat:"Bearings & Spares",code:"YK-BRG-6204",desc:"Common bearing size for motors, fans and rotating equipment.",img:"assets/product-bearing.svg",badge:"Common Size",featured:true,tags:"bearing 6204 motor ball bearing"},
{id:22,brand:"Repair Spares",name:"Mechanical Seal",model:"Pump Seal",spec:"Pump maintenance",cat:"Bearings & Spares",code:"YK-SPR-001",desc:"Replacement mechanical seal for pumps and rotating equipment.",img:"assets/product-bearing.svg",badge:"Repair",featured:false,tags:"mechanical seal pump spare"},
{id:23,brand:"Lighting",name:"LED Flood Light",model:"Outdoor Series",spec:"Outdoor / industrial",cat:"Lighting & Electronics",code:"YK-LGT-001",desc:"LED flood light for outdoor, factory and industrial lighting.",img:"assets/product-light.svg",badge:"Lighting",featured:false,tags:"led flood light outdoor"},
{id:24,brand:"Lighting",name:"LED Driver / Power Supply",model:"Replacement Unit",spec:"LED support accessory",cat:"Lighting & Electronics",code:"YK-ELC-001",desc:"Replacement driver and power module for LED products.",img:"assets/product-light.svg",badge:"Electronic",featured:false,tags:"led driver electronic power supply"}
];
let selected="All",query="",cart=JSON.parse(localStorage.getItem("yk_request_cart")||"[]");
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function save(){localStorage.setItem("yk_request_cart",JSON.stringify(cart));$("#cartCount").textContent=cart.reduce((a,b)=>a+b.qty,0)}
function renderBrandStrip(){const w=$("#brandStrip");if(w)w.innerHTML=brands.map(b=>`<span class="brand-chip">${b}</span>`).join("")}
function renderCollections(){const w=$("#collectionGrid");if(!w)return;w.innerHTML=collections.map(c=>`<article class="collection-card" data-target="${c.category}"><div class="collection-copy"><span class="collection-tag">${c.tag}</span><h3>${c.title}</h3><p>${c.text}</p><button type="button">Explore collection</button></div><div class="collection-art"><img src="${c.image}" alt="${c.title}"></div></article>`).join("");$$('.collection-card').forEach(el=>el.onclick=()=>{selected=el.dataset.target;renderFilters();renderProducts();$("#products").scrollIntoView({behavior:"smooth"})})}
function renderCats(){const w=$("#categoryGrid");w.innerHTML=categories.map(c=>`<article class="category-card" data-cat="${c.name}"><div class="category-card-top"><div class="category-icon">${c.icon}</div><img src="${c.image}" alt="${c.name}"></div><div><h3>${c.name}</h3><p>${c.desc}</p></div><small>${products.filter(p=>p.cat===c.name).length} starter products →</small></article>`).join("");$$('.category-card').forEach(el=>el.onclick=()=>{selected=el.dataset.cat;renderFilters();renderProducts();$("#products").scrollIntoView({behavior:"smooth"})})}
function renderFilters(){const all=["All",...categories.map(c=>c.name)];$("#filters").innerHTML=all.map(x=>`<button class="filter ${selected===x?"active":""}" data-filter="${x}">${x}</button>`).join("");$$('.filter').forEach(b=>b.onclick=()=>{selected=b.dataset.filter;renderFilters();renderProducts()})}
function card(p,compact=false){return `<article class="product-card ${compact?"compact":""}"><div class="product-image"><span class="badge">${p.badge}</span><img src="${p.img}" alt="${p.name} illustration"></div><div class="product-body"><div class="product-topline"><span class="brand-name">${p.brand}</span><span class="stock">CHECK STOCK</span></div><h3>${p.name}</h3><div class="product-model">${p.model}</div><div class="product-spec">${p.spec}</div><p>${p.desc}</p><span class="code">${p.code}</span><div class="product-actions"><div class="qty"><button data-minus="${p.id}">−</button><input id="qty-${p.id}" value="1" inputmode="numeric"><button data-plus="${p.id}">+</button></div><button class="add" data-add="${p.id}">Add to request</button></div></div></article>`}
function bind(scope=document){scope.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const i=document.getElementById(`qty-${b.dataset.minus}`);i.value=Math.max(1,(+i.value||1)-1)});scope.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const i=document.getElementById(`qty-${b.dataset.plus}`);i.value=Math.max(1,(+i.value||1)+1)});scope.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const id=+b.dataset.add,qty=Math.max(1,+document.getElementById(`qty-${id}`).value||1),item=cart.find(x=>x.id===id);item?item.qty+=qty:cart.push({id,qty});save();renderCart();b.textContent="Added ✓";setTimeout(()=>b.textContent="Add to request",900)})}
function renderFeatured(){const w=$("#featuredGrid");if(!w)return;w.innerHTML=products.filter(p=>p.featured).slice(0,8).map(p=>card(p,true)).join("");bind(w)}
function matches(p){const text=`${p.brand} ${p.name} ${p.model} ${p.spec} ${p.cat} ${p.code} ${p.desc} ${p.tags}`.toLowerCase();return(selected==="All"||p.cat===selected)&&(!query||text.includes(query.toLowerCase()))}
function renderProducts(){const list=products.filter(matches);$("#resultCount").textContent=`${list.length} product${list.length===1?"":"s"}`;$("#emptyState").hidden=!!list.length;$("#productGrid").style.display=list.length?"grid":"none";$("#productGrid").innerHTML=list.map(p=>card(p)).join("");bind($("#productGrid"))}
function renderCart(){save();if(!cart.length){$("#cartItems").innerHTML='<div class="cart-empty"><b>Your request cart is empty.</b><p>Add products from the catalog.</p></div>';return}$("#cartItems").innerHTML=cart.map(x=>{const p=products.find(v=>v.id===x.id);return `<div class="cart-item"><h4>${p.name}</h4><span>${p.brand} · ${p.code}</span><div class="cart-controls"><button data-cminus="${x.id}">−</button><b>${x.qty}</b><button data-cplus="${x.id}">+</button><button class="remove" data-remove="${x.id}">Remove</button></div></div>`}).join("");$$('[data-cminus]').forEach(b=>b.onclick=()=>{const x=cart.find(v=>v.id===+b.dataset.cminus);x.qty=Math.max(1,x.qty-1);renderCart()});$$('[data-cplus]').forEach(b=>b.onclick=()=>{cart.find(v=>v.id===+b.dataset.cplus).qty++;renderCart()});$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(v=>v.id!==+b.dataset.remove);renderCart()})}
function orderText(){return ["Hello YK Electric & Electronic,","","Please confirm availability and final price for:",...cart.map((x,i)=>{const p=products.find(v=>v.id===x.id);return `${i+1}. ${p.brand} ${p.name} (${p.code}) — Qty ${x.qty}`}),"","Please confirm exact model, stock, price and delivery."].join("\n")}
function openCart(){$("#drawer").classList.add("open");$("#overlay").classList.add("show");$("#drawer").setAttribute("aria-hidden","false")}
function closeCart(){$("#drawer").classList.remove("open");$("#overlay").classList.remove("show");$("#drawer").setAttribute("aria-hidden","true")}
$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#overlay").onclick=closeCart;$("#clearCart").onclick=()=>{cart=[];renderCart()};
$("#catalogSearch").oninput=e=>{query=e.target.value;renderProducts()};function heroFind(){query=$("#heroSearch").value;selected="All";$("#catalogSearch").value=query;renderFilters();renderProducts();$("#products").scrollIntoView({behavior:"smooth"})}$("#heroSearchBtn").onclick=heroFind;$("#heroSearch").onkeydown=e=>{if(e.key==="Enter")heroFind()};$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");$$('#nav a').forEach(a=>a.onclick=()=>$("#nav").classList.remove("open"));
$("#year").textContent=new Date().getFullYear();renderBrandStrip();renderCollections();renderCats();renderFeatured();renderFilters();renderProducts();renderCart();