(()=>{
  const cfg=window.YKSupabaseConfig||{},$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let file=null,headers=[],rows=[],mapping={},busy=false;
  const TYPES={
    customers:{label:'Customers',icon:'◎',key:'phone',fields:[
      ['name','Customer name',true,['name','customer','customername','party','partyname','accountname']],
      ['phone','Phone / mobile',true,['phone','mobile','mobileno','mobilenumber','phone number','phonenumber','contact','contactno','contactnumber']],
      ['business_name','Business / shop',false,['business','businessname','company','companyname','firm','firmname','shop','shopname']],
      ['location','Location / address',false,['location','address','city','place','area']],
      ['email','Email',false,['email','emailaddress']],
      ['credit_limit','Credit limit',false,['creditlimit','limit','creditamount']],
      ['credit_days','Credit days',false,['creditdays','paymentdays','days']],
      ['credit_hold','Credit hold',false,['credithold','hold','onhold']],
      ['notes','Notes',false,['notes','note','remarks','remark']]
    ]},
    suppliers:{label:'Suppliers',icon:'▤',key:'name',fields:[
      ['name','Supplier name',true,['name','supplier','suppliername','vendor','vendorname','party','partyname']],
      ['contact_person','Contact person',false,['contactperson','contactname','person']],
      ['phone','Phone / mobile',false,['phone','mobile','mobileno','phonenumber','contact','contactno']],
      ['email','Email',false,['email','emailaddress']],
      ['address','Address',false,['address','location','city','place']],
      ['tax_number','PAN / VAT number',false,['taxnumber','pan','panno','vat','vatno','panvat','panvatnumber']],
      ['notes','Notes',false,['notes','note','remarks','remark']]
    ]},
    products:{label:'Products & opening stock',icon:'◫',key:'code',fields:[
      ['name','Product / item name',true,['name','item','itemname','product','productname']],
      ['brand','Brand',false,['brand','make','company']],
      ['model','Model',false,['model','modelno','modelnumber']],
      ['specification','Specification',false,['specification','spec','size','description2']],
      ['category','Category',false,['category','group','itemgroup','productgroup']],
      ['code','Code / SKU',false,['code','sku','itemcode','productcode','barcode']],
      ['price_text','Selling price / price text',false,['price','rate','saleprice','salesprice','sellingprice','mrp']],
      ['stock_quantity','Opening stock',false,['stock','stockqty','stockquantity','quantity','qty','openingstock','closingstock']],
      ['reorder_level','Reorder level',false,['reorder','reorderlevel','minimumstock','minstock']],
      ['cost_price','Cost / purchase price',false,['cost','costprice','purchaseprice','buyingprice','purchaserate']],
      ['stock_unit','Unit',false,['unit','uom','stockunit']],
      ['track_inventory','Track inventory',false,['trackinventory','trackstock','inventory']],
      ['description','Description',false,['description','details','notes']]
    ]}
  };
  const cleanHeader=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'');
  const truthy=v=>['1','true','yes','y','on','hold'].includes(String(v||'').trim().toLowerCase());
  const num=v=>{const n=Number(String(v??'').replace(/,/g,'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?Math.max(0,n):0};
  const phoneNorm=v=>{let n=String(v||'').replace(/\D/g,'');if(n.length===10&&n.startsWith('9'))n='977'+n;return n};
  function token(){return window.YKAdminAuth?.getToken?.()||''}
  function authed(){return Boolean(window.YKAdminAuth?.isAuthenticated?.())}
  async function rest(path,options={}){if(!authed())throw new Error('Admin sign-in required.');const res=await fetch(`${cfg.url}/rest/v1/${path}`,{...options,headers:{apikey:cfg.publishableKey,Authorization:`Bearer ${token()}`,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})},cache:'no-store'});const body=await res.json().catch(()=>null);if(!res.ok)throw new Error(body?.message||body?.hint||body?.details||`Request failed (${res.status})`);return body}
  function parseCSV(text){const out=[],row=[];let cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>String(x).trim()!==''))out.push(row.splice(0));else row.length=0}else cell+=c}row.push(cell);if(row.some(x=>String(x).trim()!==''))out.push(row);return out}
  function csv(v){const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
  function inject(){const nav=$('#sideNav');if(nav&&!nav.querySelector('[data-page="import"]')){const b=document.createElement('button');b.className='nav-item';b.dataset.page='import';b.innerHTML='<span>⇩</span>Import Data';const settings=nav.querySelector('[data-page="settings"]');nav.insertBefore(b,settings||null);b.onclick=show}
    if(!$('#page-import')){const page=document.createElement('section');page.className='page';page.id='page-import';page.innerHTML=`<div class="page-heading compact"><div><p class="eyebrow">DATA ONBOARDING</p><h1>Import Center</h1><p>Bring customers, suppliers and products from Vyapar or any CSV export into YK.</p></div><span class="import-safe">Preview before import</span></div><div class="import-layout"><section class="import-card"><div class="import-step"><span>1</span><div><b>Choose data type</b><small>Start with the file you already have.</small></div></div><div class="import-controls"><select id="importType"><option value="customers">Customers</option><option value="suppliers">Suppliers</option><option value="products">Products & opening stock</option></select><button class="ghost-btn" id="importTemplate">Download CSV template</button></div><label class="import-drop" id="importDrop"><input id="importFile" type="file" accept=".csv,text/csv" hidden><span>⇩</span><b>Drop a CSV file here</b><small>or click to choose a Vyapar / spreadsheet CSV export</small></label><div id="importFileInfo" class="import-file-info" hidden></div></section><section class="import-card" id="importMapCard" hidden><div class="import-step"><span>2</span><div><b>Match columns</b><small>YK automatically matches common Vyapar and spreadsheet headings.</small></div></div><div id="importMapping" class="import-mapping"></div></section><section class="import-card" id="importPreviewCard" hidden><div class="import-step"><span>3</span><div><b>Review before import</b><small>Invalid rows are skipped. Nothing is changed until you press Import.</small></div></div><div class="import-options"><label>Duplicates<select id="importDuplicateMode"><option value="update">Update existing records</option><option value="skip">Skip existing records</option></select></label><div id="importValidation" class="import-validation"></div></div><div class="import-preview-wrap"><table class="import-preview"><thead id="importPreviewHead"></thead><tbody id="importPreviewBody"></tbody></table></div><div class="import-actions"><button class="ghost-btn" id="importReset">Choose another file</button><button class="primary-btn" id="importRun">Import valid rows</button></div><div id="importResult" class="import-result" hidden></div></section></div>`;$('.main-panel')?.appendChild(page);$('#importType').onchange=()=>resetFile();$('#importTemplate').onclick=downloadTemplate;$('#importFile').onchange=e=>loadFile(e.target.files?.[0]);const drop=$('#importDrop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');loadFile(e.dataTransfer.files?.[0])};$('#importReset').onclick=resetFile;$('#importRun').onclick=runImport}
  }
  function show(){inject();document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));$('#page-import')?.classList.add('active');document.querySelector('[data-page="import"]')?.classList.add('active');if($('#pageTitle'))$('#pageTitle').textContent='Import Center';$('#sidebar')?.classList.remove('open')}
  function resetFile(){file=null;headers=[];rows=[];mapping={};const input=$('#importFile');if(input)input.value='';$('#importFileInfo').hidden=true;$('#importMapCard').hidden=true;$('#importPreviewCard').hidden=true;$('#importResult').hidden=true;$('#importDrop')?.classList.remove('loaded')}
  async function loadFile(f){if(!f)return;if(!/\.csv$/i.test(f.name)){alert('Please choose a CSV file. In Excel or Vyapar, export/save the file as CSV first.');return}file=f;const text=await f.text();const matrix=parseCSV(text.replace(/^\uFEFF/,''));if(matrix.length<2){alert('This CSV has no data rows.');return}headers=matrix[0].map(x=>String(x).trim());rows=matrix.slice(1).map(r=>{const o={};headers.forEach((h,i)=>o[h]=String(r[i]??'').trim());return o}).filter(o=>Object.values(o).some(Boolean));autoMap();$('#importFileInfo').hidden=false;$('#importFileInfo').innerHTML=`<b>${esc(f.name)}</b><span>${rows.length.toLocaleString()} rows · ${headers.length} columns</span>`;$('#importDrop')?.classList.add('loaded');$('#importMapCard').hidden=false;$('#importPreviewCard').hidden=false;renderMapping();renderPreview()}
  function autoMap(){const type=TYPES[$('#importType')?.value||'customers'];mapping={};const source=new Map(headers.map(h=>[cleanHeader(h),h]));type.fields.forEach(([key,,required,aliases])=>{const candidates=[key,...aliases].map(cleanHeader);mapping[key]=candidates.map(a=>source.get(a)).find(Boolean)||''})}
  function renderMapping(){const type=TYPES[$('#importType').value],h=$('#importMapping');h.innerHTML=type.fields.map(([key,label,required])=>`<label><span>${esc(label)}${required?' *':''}</span><select data-map="${key}"><option value="">— Not mapped —</option>${headers.map(x=>`<option value="${esc(x)}" ${mapping[key]===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`).join('');h.querySelectorAll('[data-map]').forEach(s=>s.onchange=()=>{mapping[s.dataset.map]=s.value;renderPreview()})}
  function mappedRows(){const type=TYPES[$('#importType').value];return rows.map((source,index)=>{const out={__row:index+2};type.fields.forEach(([key])=>out[key]=mapping[key]?String(source[mapping[key]]??'').trim():'');return out})}
  function validation(){const type=TYPES[$('#importType').value],mapped=mappedRows(),required=type.fields.filter(x=>x[2]).map(x=>x[0]),valid=[],invalid=[];mapped.forEach(r=>{const missing=required.filter(k=>!String(r[k]||'').trim());if(type===TYPES.customers&&r.phone&&phoneNorm(r.phone).length<7)missing.push('valid phone');(missing.length?invalid:valid).push({...r,__error:missing.join(', ')})});return{mapped,valid,invalid}}
  function renderPreview(){if(!rows.length)return;const type=TYPES[$('#importType').value],{mapped,valid,invalid}=validation(),keys=type.fields.filter(([k])=>mapping[k]).map(x=>x[0]),labels=new Map(type.fields.map(x=>[x[0],x[1]]));$('#importPreviewHead').innerHTML=`<tr><th>Row</th>${keys.slice(0,6).map(k=>`<th>${esc(labels.get(k))}</th>`).join('')}<th>Status</th></tr>`;$('#importPreviewBody').innerHTML=mapped.slice(0,8).map(r=>{const bad=invalid.find(x=>x.__row===r.__row);return `<tr class="${bad?'invalid':''}"><td>${r.__row}</td>${keys.slice(0,6).map(k=>`<td>${esc(r[k]||'—')}</td>`).join('')}<td><span class="import-row-status ${bad?'bad':'good'}">${bad?'Skip':'Ready'}</span></td></tr>`}).join('');const requiredMissing=type.fields.filter(x=>x[2]&&!mapping[x[0]]);$('#importValidation').innerHTML=requiredMissing.length?`<b class="bad">Map required field${requiredMissing.length>1?'s':''}: ${requiredMissing.map(x=>esc(x[1])).join(', ')}</b>`:`<b>${valid.length} ready</b><span>${invalid.length} invalid / blank row${invalid.length===1?'':'s'} will be skipped</span>`;$('#importRun').disabled=Boolean(requiredMissing.length)||!valid.length}
  function downloadTemplate(){const type=TYPES[$('#importType').value],header=type.fields.map(x=>csv(x[0])).join(',')+'\n',blob=new Blob([header],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`yk-${$('#importType').value}-template.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function prepareCustomer(r){return{name:r.name||'Customer',phone:r.phone,phone_normalized:phoneNorm(r.phone),business_name:r.business_name||null,location:r.location||null,email:r.email||null,status:'customer',notes:r.notes||null,credit_limit:num(r.credit_limit),credit_days:Math.round(num(r.credit_days)),credit_hold:truthy(r.credit_hold),updated_at:new Date().toISOString(),last_activity_at:new Date().toISOString()}}
  function prepareSupplier(r){return{name:r.name,contact_person:r.contact_person||null,phone:r.phone||null,email:r.email||null,address:r.address||null,tax_number:r.tax_number||null,notes:r.notes||null,active:true,updated_at:new Date().toISOString()}}
  function priceText(v){const s=String(v||'').trim();if(!s)return'Price on request';const n=Number(s.replace(/,/g,''));return Number.isFinite(n)?`Rs. ${n.toLocaleString('en-NP',{maximumFractionDigits:2})}`:s}
  function prepareProduct(r,id){const q=num(r.stock_quantity),re=num(r.reorder_level),cost=num(r.cost_price),track=r.track_inventory?truthy(r.track_inventory):(q>0||re>0||cost>0);return{id,brand:r.brand||'Unbranded',name:r.name,model:r.model||null,specification:r.specification||null,category:r.category||'General',code:r.code||null,description:r.description||null,price_text:priceText(r.price_text),stock_status:track?(q>0?'In Stock':'Out of Stock'):'Check Stock',active:true,stock_quantity:q,reorder_level:re,cost_price:cost,stock_unit:r.stock_unit||'pcs',track_inventory:track,updated_at:new Date().toISOString()}}
  async function chunks(items,size,fn){for(let i=0;i<items.length;i+=size)await Promise.all(items.slice(i,i+size).map(fn))}
  async function importCustomers(valid,mode){const existing=await rest('customers?select=id,phone_normalized'),set=new Set(existing.map(x=>x.phone_normalized)),prepared=valid.map(prepareCustomer),todo=mode==='skip'?prepared.filter(x=>!set.has(x.phone_normalized)):prepared,skipped=prepared.length-todo.length;if(todo.length){for(let i=0;i<todo.length;i+=100)await rest('customers?on_conflict=phone_normalized',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(todo.slice(i,i+100))})}return{imported:todo.length,skipped}}
  async function importSuppliers(valid,mode){const existing=await rest('suppliers?select=id,name'),map=new Map(existing.map(x=>[String(x.name).trim().toLowerCase(),x])),newRows=[],updates=[],seen=new Set();for(const r of valid){const p=prepareSupplier(r),key=p.name.trim().toLowerCase(),hit=map.get(key);if(hit){if(mode==='update')updates.push([hit.id,p])}else if(!seen.has(key)){newRows.push(p);seen.add(key)}}if(newRows.length)for(let i=0;i<newRows.length;i+=100)await rest('suppliers',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(newRows.slice(i,i+100))});await chunks(updates,10,([id,p])=>rest(`suppliers?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(p)}));return{imported:newRows.length+updates.length,skipped:valid.length-newRows.length-updates.length}}
  async function importProducts(valid,mode){const existing=await rest('products?select=id,code,name,brand,model&order=id.asc'),byCode=new Map(existing.filter(x=>x.code).map(x=>[String(x.code).trim().toLowerCase(),x])),byName=new Map(existing.map(x=>[[x.name,x.brand,x.model||''].map(v=>String(v||'').trim().toLowerCase()).join('|'),x])),max=Math.max(0,...existing.map(x=>Number(x.id)||0));let next=max+1;const newRows=[],updates=[];for(const r of valid){const code=String(r.code||'').trim().toLowerCase(),key=[r.name,r.brand||'Unbranded',r.model||''].map(v=>String(v||'').trim().toLowerCase()).join('|'),hit=(code&&byCode.get(code))||byName.get(key);if(hit){if(mode==='update'){const p=prepareProduct(r,Number(hit.id));delete p.id;updates.push([hit.id,p])}}else{const p=prepareProduct(r,next++);newRows.push(p);if(code)byCode.set(code,p);byName.set(key,p)}}if(newRows.length)for(let i=0;i<newRows.length;i+=75)await rest('products',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(newRows.slice(i,i+75))});await chunks(updates,8,([id,p])=>rest(`products?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(p)}));return{imported:newRows.length+updates.length,skipped:valid.length-newRows.length-updates.length}}
  async function runImport(){if(busy||!authed())return;const {valid,invalid}=validation();if(!valid.length)return;const type=$('#importType').value,mode=$('#importDuplicateMode').value,btn=$('#importRun'),result=$('#importResult');if(!confirm(`Import ${valid.length} valid ${TYPES[type].label.toLowerCase()} into YK? ${mode==='update'?'Matching records will be updated.':'Existing matches will be skipped.'}`))return;busy=true;btn.disabled=true;btn.textContent='Importing…';result.hidden=true;try{let summary;if(type==='customers')summary=await importCustomers(valid,mode);else if(type==='suppliers')summary=await importSuppliers(valid,mode);else summary=await importProducts(valid,mode);const totalSkipped=summary.skipped+invalid.length;result.hidden=false;result.className='import-result success';result.innerHTML=`<b>Import complete ✓</b><span>${summary.imported} record${summary.imported===1?'':'s'} imported / updated${totalSkipped?` · ${totalSkipped} skipped`:''}.</span>${type==='products'?'<small>Product data is now in Supabase. Refresh Cloud once to sync the Admin catalog view.</small>':''}`;document.dispatchEvent(new CustomEvent('yk-data-imported',{detail:{type,...summary}}));if(type==='products')sessionStorage.removeItem('yk_supabase_admin_loaded')}catch(e){result.hidden=false;result.className='import-result error';result.innerHTML=`<b>Import stopped</b><span>${esc(e.message)}</span>`}finally{busy=false;btn.disabled=false;btn.textContent='Import valid rows'}}
  inject();document.addEventListener('yk-admin-authenticated',inject);window.YKImport={show,reset:resetFile};
})();