alter table public.enquiries
  add column if not exists contact_preference text not null default 'whatsapp',
  add column if not exists required_timeline text not null default 'planning',
  add column if not exists priority text not null default 'normal',
  add column if not exists next_follow_up_at timestamptz,
  add column if not exists last_contact_at timestamptz,
  add column if not exists admin_notes text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'enquiries_contact_preference_check'
      and conrelid = 'public.enquiries'::regclass
  ) then
    alter table public.enquiries
      add constraint enquiries_contact_preference_check
      check (contact_preference in ('whatsapp','phone','either'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'enquiries_required_timeline_check'
      and conrelid = 'public.enquiries'::regclass
  ) then
    alter table public.enquiries
      add constraint enquiries_required_timeline_check
      check (required_timeline in ('urgent','2-3-days','this-week','planning'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'enquiries_priority_check'
      and conrelid = 'public.enquiries'::regclass
  ) then
    alter table public.enquiries
      add constraint enquiries_priority_check
      check (priority in ('low','normal','high','urgent'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'enquiries_admin_notes_length'
      and conrelid = 'public.enquiries'::regclass
  ) then
    alter table public.enquiries
      add constraint enquiries_admin_notes_length
      check (admin_notes is null or char_length(admin_notes) <= 4000);
  end if;
end
$$;

create index if not exists idx_enquiries_follow_up_active
  on public.enquiries(next_follow_up_at)
  where next_follow_up_at is not null
    and status in ('new','contacted','quoted','confirmed');

create index if not exists idx_enquiries_priority_created
  on public.enquiries(priority, created_at desc)
  where status in ('new','contacted','quoted','confirmed');

create table if not exists public.enquiry_activity (
  id bigint generated by default as identity primary key,
  enquiry_id uuid not null references public.enquiries(id) on delete cascade,
  action text not null check (action in ('created','status_changed','priority_changed','follow_up_scheduled','note_updated','contact_logged')),
  note text check (note is null or char_length(note) <= 1000),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_enquiry_activity_enquiry_created
  on public.enquiry_activity(enquiry_id, created_at desc);

alter table public.enquiry_activity enable row level security;

drop policy if exists "admins manage enquiry activity" on public.enquiry_activity;
create policy "admins manage enquiry activity"
  on public.enquiry_activity
  for all
  to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

create or replace function private.track_enquiry_changes()
returns trigger
language plpgsql
security invoker
set search_path = public, private, pg_temp
as $function$
begin
  if old.status is distinct from new.status then
    insert into public.enquiry_activity(enquiry_id,action,note)
    values(new.id,'status_changed',initcap(replace(old.status,'_',' ')) || ' → ' || initcap(replace(new.status,'_',' ')));
  end if;

  if old.priority is distinct from new.priority then
    insert into public.enquiry_activity(enquiry_id,action,note)
    values(new.id,'priority_changed',initcap(old.priority) || ' → ' || initcap(new.priority));
  end if;

  if old.next_follow_up_at is distinct from new.next_follow_up_at then
    insert into public.enquiry_activity(enquiry_id,action,note)
    values(
      new.id,
      'follow_up_scheduled',
      case
        when new.next_follow_up_at is null then 'Follow-up schedule cleared.'
        else 'Next follow-up: ' || to_char(new.next_follow_up_at at time zone 'Asia/Kathmandu','Mon DD, YYYY HH24:MI') || ' NPT'
      end
    );
  end if;

  if old.admin_notes is distinct from new.admin_notes then
    insert into public.enquiry_activity(enquiry_id,action,note)
    values(new.id,'note_updated','Internal sales notes revised.');
  end if;

  return new;
end;
$function$;

revoke all on function private.track_enquiry_changes() from public, anon, authenticated;

drop trigger if exists track_enquiry_changes on public.enquiries;
create trigger track_enquiry_changes
after update of status, priority, next_follow_up_at, admin_notes on public.enquiries
for each row execute function private.track_enquiry_changes();

create or replace function public.submit_enquiry_v2(
  p_customer_name text,
  p_phone text,
  p_business_name text,
  p_location text,
  p_notes text,
  p_contact_preference text,
  p_required_timeline text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $function$
declare
  v_result jsonb;
  v_id uuid;
  v_preference text := lower(trim(coalesce(p_contact_preference,'whatsapp')));
  v_timeline text := lower(trim(coalesce(p_required_timeline,'planning')));
begin
  if v_preference not in ('whatsapp','phone','either') then
    raise exception 'Choose a valid contact preference';
  end if;

  if v_timeline not in ('urgent','2-3-days','this-week','planning') then
    raise exception 'Choose a valid required timeline';
  end if;

  v_result := public.submit_enquiry(
    p_customer_name,
    p_phone,
    p_business_name,
    p_location,
    p_notes,
    p_items
  );

  v_id := (v_result->>'id')::uuid;
  if coalesce((v_result->>'duplicate')::boolean,false) = false then
    update public.enquiries
    set contact_preference = v_preference,
        required_timeline = v_timeline,
        priority = case when v_timeline = 'urgent' then 'high' else 'normal' end,
        updated_at = now()
    where id = v_id;

    insert into public.enquiry_activity(enquiry_id,action,note,created_by)
    values(v_id,'created','Website enquiry received and added to the sales inbox.',null);
  end if;

  return v_result;
end;
$function$;

revoke all on function public.submit_enquiry_v2(text,text,text,text,text,text,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.submit_enquiry_v2(text,text,text,text,text,text,text,jsonb)
  to anon, authenticated, service_role;

-- Explicit Data API grants keep anonymous storefront access read-only.
revoke all on table public.products, public.brands, public.categories, public.homepage_trending, public.store_settings
  from anon;
grant select on table public.products, public.brands, public.categories, public.homepage_trending, public.store_settings
  to anon;

revoke all on table public.enquiries, public.enquiry_items, public.admin_profiles, public.enquiry_activity
  from anon;

revoke all on table public.products, public.brands, public.categories, public.homepage_trending, public.store_settings,
  public.enquiries, public.enquiry_items, public.enquiry_activity
  from authenticated;
grant select, insert, update, delete on table public.products, public.brands, public.categories,
  public.homepage_trending, public.store_settings, public.enquiries, public.enquiry_items, public.enquiry_activity
  to authenticated;

revoke all on table public.admin_profiles from authenticated;
grant select, insert on table public.admin_profiles to authenticated;

grant usage, select on sequence public.enquiry_activity_id_seq to authenticated, service_role;

notify pgrst, 'reload schema';
